### ISSUE TITLE
Adding a prefix to the aggregate in the router breaks the strong consistency of the router

### ISSUE THREAD

**Issue by tcoopman** [slashdotdash/commanded#101]
When you add a prefix to an AggregateRoot in the Router:

```elixir
  defmodule ConsistencyRouter do
    use Commanded.Commands.Router

    identify ConsistencyAggregateRoot,
        by: :uuid,
        prefix: "some-prefix"

    dispatch [ConsistencyCommand,NoOpCommand,RequestDispatchCommand],
      to: ConsistencyAggregateRoot
  end
```

and then try to use `Router.dispatch(..., consistency: :strong)` it never returns `:ok`, but always `{:error, :consistency_timeout}`. You can easily test this in the `dispatch_consistency_test.exs`

**Comment by slashdotdash** [comment]
Thanks for the bug report @tcoopman, I will take a look. Expect it to be a straightforward fix - the consistency check is using the `aggregate_uuid`, which in the case of using a prefix will be different from the actual `stream_uuid` used to persist its events.

**Comment by slashdotdash** [comment]
Fixed, will be available in the next release of Commanded.
