### ISSUE TITLE
Command handling middleware

### ISSUE THREAD

**Issue by slashdotdash** [slashdotdash/commanded#12]
Allow a command router to define middleware modules that are executed before, after and on failure of each command dispatch. 

This provides an extension point to add in command validation, authorization, logging, etc. Typical behaviour that you want to be called for *every* command the router dispatches.

It will follow the [middleware approach taken by Exq]https://github.com/akira/exq#middleware-support].

``` elixir
defmodule BankingRouter do
  use Commanded.Commands.Router

  middleware Commanded.Logger
  middleware MyCommandValidator
  middleware AuthorizeCommand

  dispatch OpenAccount, to: OpenAccountHandler, aggregate: BankAccount, identity: :account_number
  dispatch DepositMoney, to: DepositMoneyHandler, aggregate: BankAccount, identity: :account_number
end
```

The middleware modules will be executed in the order they’ve been defined. They will receive a struct containing the command being dispatched.

### Module middleware

``` elixir
defmodule MyMiddleware do
  @behaviour Commanded.Commands.Middleware

  def before_dispatch(%{command: command} = pipeline) do   
    pipeline
  end

  def after_dispatch(%{command: command} = pipeline) do   
    pipeline
  end

  def after_failure(%{} = pipeline) do   
    pipeline
  end
end
```

**Comment by henry-hz** [comment]
Very cool feature. 
The EXQ lib has a cool pipeline implementation, without macros.
https://github.com/akira/exq

**Comment by slashdotdash** [comment]
@henry-hz Just had a look at the Exq middleware approach. That could be useful guidance for implementing this feature. `Commanded.Commands.Router` is already a macro, so that could just provide the configuration of the pipeline. Execution will be plain old Elixir code.

**Comment by slashdotdash** [comment]
I've updated the issue description to follow the Exq middleware approach. I think that provides a clean API and should be straightforward to implement.
