### ISSUE TITLE
Retry event handler and process manager on error

### ISSUE THREAD

**Issue by slashdotdash** [slashdotdash/commanded#20]
Event handlers and process managers are expected to return `:ok` on successful handling of an event. They return `{:error, reason}` on failure. In this case the event handler should be retried. 

Potential error handling options: retry, skip, ignore, stop, or park event.

**Comment by Papipo** [comment]
Maybe skipping the event is not always a viable option depending on the domain. I guess that failing is a must in many scenarios. Maybe there is a bug that has to be fixed and skipping some events leads to inconsistent state.

**Comment by slashdotdash** [comment]
@Papipo Skip event on error could be made configurable, either per event handler or globally.

**Comment by slashdotdash** [comment]
Could use [tarearbol](https://github.com/am-kantox/tarearbol) to provide retry logic.

**Comment by drozzy** [comment]
I see no need for this.

1. Crash the app.
2. App restarts as defined pre restart policy.
3. Event gets delivered again.
4. App may crash again. After erlang-defined crash semantics exceed the threshold the BEAM shuts down.
5. Upper level machinery (e.g. docker) may restart the server.

This works great for my own cases (where I hand-built my process managers). Can't see why commanded would not succeed with this simple approach as well.

**Comment by astery** [comment]
@drozzy, I think you talking about scenario when process manager generally fails (all process manager instances are failed), it's definitely should result app crash.

And I think proposal about - why crash the whole application if only one specific process manager instance fails? Just submit log, and stop executing bad process manager instance, or try another restart policy (like dropping state or skip event).

**Comment by slashdotdash** [comment]
@drozzy Providing an extension point allows consumers of Commanded finer control over how they deal with errors on a case by case basis. So you could decide that for a certain event handler, or particular event, it should retry X times with exponential back-off between retries. Another handler could simply skip any problematic events. 

I don't know exactly what the best strategy is for each use case, therefore make it user configurable.

**Comment by drozzy** [comment]
Seems like this can be done with some [external ](https://github.com/ferd/backoff) dependency in client code. Is there any actual uses for this? 

_P.S.: I quite like Gregg's approach to [features](https://youtu.be/GRr4xeMn1uU)._

**Comment by slashdotdash** [comment]
Closing this issue. Replaced by #93 to support error handling for process manager command dispatch only.
