### ISSUE TITLE
Supervisor restarts aggregate, that loses command routing and remains pending.

### ISSUE THREAD

**Issue by henry-hz** [slashdotdash/commanded#21]
When we start a new aggregate, and kill it, supervisor immediately restart it with the last state, replaying all the events. But when sending a new Command to the same aggregate UUID, a new aggregate is created, and updated, so we end up with two aggregates on memory, one unusable (and consumed resources to be restarted) and a new fresh one, that was started by the last command request.  Using :observer.start can help to track their state and see what is going on. Pls, let me know if you need more details to reproduce it.

**Comment by henry-hz** [comment]
created a PR

**Comment by slashdotdash** [comment]
Thanks for the pull request, merged.
