### ISSUE TITLE
Routing using GenEvent

### ISSUE THREAD

**Issue by henry-hz** [slashdotdash/commanded#23]
Dear @slashdotdash , let me ask you why all the routing structure for handling commands and events, wouldn't be easier to use the GenEvent framework instead ?
thanks

**Comment by slashdotdash** [comment]
GenEvent was not suitable for a few reasons.
 
1. For command dispatching in CQRS there must be exactly one registered handler for each command. Not having a handler, or more than one, configured is an error. 
2. GenEvent doesn't guarantee delivery of events. If a subscriber process goes down, it will miss any events published until it restarts. 
3. All GenEvent handlers run in a single process.

In comparison, each Commanded event handler has its own subscription to the event store. It acknowledges every event it receives and successfully processes. This allows it to resume in the event of a process crash, or catch up if it is lagging behind. It also allows new subscribers to be added and they can receive every event published from the event stream origin.

**Comment by henry-hz** [comment]
Got it, it's an elegant design :100: 

For the reason 1, it's okay, the developer can pay attention if the system is small, and if the system is too big, a consistency test tool can track commands, events and errors, and alert if they are inconsistent with the CQRS rules, or if some command was lost and no event or feedback was emitted.  For the reason 2 and 3, seems that GenStage comes to solve them: http://elixir-lang.org/blog/2016/07/14/announcing-genstage/ . Please, let me know if makes sense.

**Comment by slashdotdash** [comment]
GenStage could be useful for event handling. I've taken a look at it before. Its approach to broadcast is to wait for every subscriber. This may not be appropriate if you have independent event handlers that you don't want to be blocked by the slowest handler. Back pressure has already been implemented for Commanded's event handlers.

**Comment by Papipo** [comment]
I think that GenStage producers can provide input for any consumer that requests demand.
Besides, there is an experimental PartitionDispatcher which makes a lot of sense for event sourcing.

**Comment by Papipo** [comment]
For the record, I have read at least a couple of articles advising against using gen_event.

**Comment by henry-hz** [comment]
Yep, also read, seems we should avoid it.
