### ISSUE TITLE
Process Manager Instance doesn't die after reaching the final state

### ISSUE THREAD

**Issue by henry-hz** [slashdotdash/commanded#24]
When manually sending TransferMoney commands, like the one below, and checking it's creation in the Observer, I noted that after the process is finished, it continues there pending.  After reaching the final state, the process could suicide, and a TTL also would be suitable for high loading, and cache only what is in real use.  Please, let me ask you to comment how commanded is in production, some benchmarks.
thanks :)

:ok = Bank.Router.dispatch(%TransferMoney{source_account: "ACC333", target_account: "ACC123", amount: 5})

**Comment by slashdotdash** [comment]
Commanded is not used in production right now. I'm building a web app that uses it and am hoping to have it deployed before the end of the year. 

Extending process managers to allow an instance to signal that it has finished is a useful feature to have. It could be done by extended `interested?` to support `:start`, `:continue`, and `:end`. Example with the possible change taken from the README below.

```elixir
defmodule TransferMoneyProcessManager do
  # ...

  def interested?(%MoneyTransferRequested{transfer_uuid: transfer_uuid}), do: {:start, transfer_uuid}
  def interested?(%MoneyWithdrawn{transfer_uuid: transfer_uuid}), do: {:continue, transfer_uuid}
  def interested?(%MoneyDeposited{transfer_uuid: transfer_uuid}), do: {:continue, transfer_uuid}
  def interested?(%MoneyTransferCompleted{transfer_uuid: transfer_uuid}), do: {:end, transfer_uuid}
  def interested?(_event), do: false
  
 # ...
end
```

A second feature of stopping process manager instance processes that have been running idle for a period of time is another useful feature to add. This also applies to aggregate instances.

**Comment by slashdotdash** [comment]
A process manager instance should also remove its snapshot data from storage once it has ended. Before the process terminates.
