### ISSUE TITLE
Use Elixir 1.4 Registry for aggregates

### ISSUE THREAD

**Issue by slashdotdash** [slashdotdash/commanded#38]
Replace [registry.ex](https://github.com/slashdotdash/commanded/blob/master/lib/commanded/aggregates/registry.ex) with the new [Registry module in Elixir 1.4](https://github.com/elixir-lang/elixir/blob/v1.4/CHANGELOG.md#registry).

**Comment by Papipo** [comment]
I would create a wrapped to allow configuring different registry backends, as mentioned [here](https://github.com/slashdotdash/commanded/issues/34#issuecomment-262517622).

**Comment by henry-hz** [comment]
See http://www.ostinelli.net/an-evaluation-of-erlang-global-process-registries-meet-syn/ , comparing them.  [BPE](https://github.com/spawnproc/bpe) choice was SYN

**Comment by slashdotdash** [comment]
@Papipo Supporting [Swarm](https://github.com/bitwalker/swarm) would be a really good medium/long-term goal. Commanded is currently restricted to running on a single node. Supporting multi-node would provide horizontal scalability. 

The issue is that you cannot just swap in a distributed process registry. You must ensure certain processes only run on a single node (e.g. aggregate root process, process mangers, event subscriptions). This only really becomes a problem during net-split scenarios (temporary/permanent) and how you rebalance processes across nodes as they come up or go down. 

Swarm requires you to support its own API in your GenServer (`:begin_handoff`, `:end_handoff`, `resolve_conflict`, and `die`). 

The immediate gain is to swap to Elixir's Registry for it's better support and performance. To replace the existing `GenServer` state that maps aggregate UUIDs to PIDs.

**Comment by Papipo** [comment]
Correct, as long as it's on the roadmap I'm ok with that 👍

**Comment by slashdotdash** [comment]
Done by #48.
