### ISSUE TITLE
Support for multiple MQs, Rabbit, Google PUBSUB, etc...

### ISSUE THREAD

**Issue by henry-hz** [slashdotdash/commanded#40]
We can start with tinyMQ
https://github.com/ChicagoBoss/tinymq

**Comment by slashdotdash** [comment]
What's the use case for supporting multiple message queues? 

A consumer of Commanded can write an event handler that pushes events straight onto any message queue they choose to use.

**Comment by henry-hz** [comment]
Maybe a "one point" contract adapter, like: https://github.com/ChicagoBoss/ChicagoBoss/blob/master/src/boss/mq_adapters/boss_mq_adapter_tinymq.erl

**Comment by slashdotdash** [comment]
I'm still unsure what you want to use it for, and why it needs to be implemented here?

**Comment by henry-hz** [comment]
I thought that if we could generalize the MQ  in a behavior (or plugin), easily one could migrate from one MQ to another. Example, the registry sends one command using point-to-point pattern to aggregate instance; An abstract layer between this communication could easy the user to use Rabbit MQ, or other. Also with event messages, one could 'subscribe' to this abstract layer, and easily use Rabbit to queue messages and process them, instead of using the eventstore.  Maybe I should study better Commanded and it's an idea "out of the bounded context"

**Comment by Papipo** [comment]
I only find this useful to integrate with legacy code.

**Comment by henry-hz** [comment]
or to delegate at-least-once deliver and de-duplication...https://github.com/pawelkaczor/akka-ddd/wiki/Reliable-Delivery

**Comment by slashdotdash** [comment]
Closing this issue. You can use an event handler to push events onto whichever message bus you like.
