### ISSUE TITLE
Shutdown idle aggregate processes

### ISSUE THREAD

**Issue by slashdotdash** [slashdotdash/commanded#43]
An aggregate process that has been idle for a configured period of time should be shutdown.

`GenServer`s have built in support for timeouts. You include a timeout value when replying to a `handle_call` or `handle_cast` request. If no subsequent requests are made to your GenServer in the timeout period it sends `:timeout` to `handle_info`. You can then shutdown the process.

**Comment by henry-hz** [comment]
maybe add a mechanism to generate an event before shutdown, so sagas will be able to reverse any long transaction ?

**Comment by Papipo** [comment]
It doesn't make sense that aggregates emit events because they haven't been receiving commands lately.

**Comment by henry-hz** [comment]
yep, agree.  there are two reasons to shutdown, or the business process was finished, or we need more memory, and that aggregate has been sparsely used. for the first, the PM could shutdown them sending stop commands, but for the former, the solution above is fine. an algorithm could calculate the desired "cache" memory, and sets the best timeout based on memory needs

**Comment by Papipo** [comment]
I guess that this is one of those cases that depends on the use case. Providing configurable timeouts would probable suffice. It's just a matter of finding a good value for your application.

**Comment by bbhoss** [comment]
Hibernating after a timeout could also be a good idea, since it will reduce memory to be as small as possible. You could probably have a timeout handler that registers (probably in ETS/Registry) the process somewhere as "in hibernation", with the current time, then have some sort of reaper that decides when to kill/shutdown processes. This is a common issue in actor languages, and why Pony was built to allow garbage collecting the actors themselves, which seems like a pretty rare/one of a kind ability.

**Comment by slashdotdash** [comment]
@bbhoss GenServer already has support for handling timeouts. You can return a `timeout` (in milliseconds) as part of the reply to `handle_cast` and `handle_call` requests. If there are no subsequent requests within the given timeout period, the GenServer will receive a `:timeout` message and can be stopped. 

It *just* needs to be implemented for the aggregate GenServer.

**Comment by bbhoss** [comment]
I understand that, what I'm proposing is in the timeout message handler, we register as hibernated, then return a `:hibernate` tuple. Then a configurable reaper could evict the processes later.

**Comment by slashdotdash** [comment]
Done in #57.

**Comment by slashdotdash** [comment]
Published to Hex as [v0.11.0](https://hex.pm/packages/commanded/0.11.0)
