### ISSUE TITLE
Validate command dispatch registration in router

### ISSUE THREAD

**Issue by slashdotdash** [slashdotdash/commanded#59]
When using the `Commanded.Commands.Router` to configure command dispatch, it would be helpful to validate that the command, handler, and aggregate modules exist.

In the following example, if the two module `alias` statements are forgotten then command dispatch will fail (`UndefinedFunctionError` module is not available).
```elixir
defmodule MyApp.BankRouter do
  use Commanded.Commands.Router

  alias MyApp.OpenAccount
  alias MyApp.BankAccount

  dispatch OpenAccount, to: BankAccount, identity: :account_number
end
```

Instead, this should cause a compilation failure, prompting the user that the modules cannot be found.

**Comment by astery** [comment]
Definitely, stumbled on that several times.
