### ISSUE TITLE
Don't read from configuration in compiletime macros

### ISSUE THREAD

**Issue by timbuchwaldt** [slashdotdash/commanded#66]
Hey!
I was trying out a sample app with commanded and changed my backing eventstore - but Commanded kept coming back to the InMemory store - which wasn't what my config set. Reinstalling + compiling fixed this.
I assume the problem is https://github.com/slashdotdash/commanded/blob/master/lib/commanded/event_store/event_store.ex#L13

**Comment by slashdotdash** [comment]
Thanks for a the bug report. I'll test what happens when you force a recompile (`mix compile --force`) and add a note to the README if that solves the issue. It's unlikely that a user will swap event store providers more than once after initial setup. The macro provides convenient, and quick, access to the module.

**Comment by timbuchwaldt** [comment]
I think you could quote this code. It should be equally fast (as it will be evaluated at compiletime as well) but the expansion will happen at compiletime of the module that uses `Commanded.EventStore`. But thats guesswork now :D

**Comment by slashdotdash** [comment]
Yes, that's exactly what it should be doing. Thanks for the pointer, want to submit a pull request with the change ;-)

**Comment by timbuchwaldt** [comment]
I tried it locally, sadly my (poor) understanding of the macro system let to no improvement on this.

**Comment by slashdotdash** [comment]
That's a shame, not to worry though. I'll take a look.

**Comment by slashdotdash** [comment]
I've done some testing on this issue. It appears to be ok if you force a recompile of Commanded after making the config change.

To verify, I added logging to the `Commanded.EventStore` macro to output the configured adapter:

```elixir
defmodule Commanded.EventStore do
  defmacro __using__(_) do
    adapter = Application.get_env(:commanded, :event_store_adapter) || raise ArgumentError, "Commanded expects :event_store_adapter to be configured in environment"
    IO.puts "event store adapter: #{inspect adapter}"

    quote do
      @event_store unquote(adapter)
    end
  end
end
```

Then I configured my app to use the in-memory adapter:

```console
$ mix deps.compile commanded --force
==> commanded
Compiling 37 files (.ex)
event store adapter: Commanded.EventStore.Adapters.InMemory
...
```

I changed the config in my app to use the event store adapter and forced a recompile:

```console
$ mix deps.compile commanded --force
==> commanded
Compiling 37 files (.ex)
event store adapter: Commanded.EventStore.Adapters.EventStore
...
```

So given that outcome, I've updated the README to include the above *force recompile* step when installing, or changing between, event store adapters.
