### ISSUE TITLE
Will event deserialization work with a different namespace?

### ISSUE THREAD

**Issue by drozzy** [slashdotdash/commanded#69]
_First of all, I wanted to say that this library is great. Thank you for your hard work. It took my codebase from over 800 LOC to about 100!_

I see that a namespaced event is serialized like so:

`Elixir.Foo.Events.BurgerRequested`

Let's say I have a different node, with a module called `Bar` which has a re-difinition of that event in the module `Bar.Events.BurgerRequested`. 

In this case, if I were to start commanded on that second note, would it expect `Elixir.Bar.Events.BurgerRequested`?

If yes, is there a way to specify how these things are mapped?

P.S.: If this is not possible, it's not a big deal to parse these things myself. Aggregates are really the biggest PITA to implement, so this would just be a cherry on top for PMs or Projections.

**Comment by slashdotdash** [comment]
@drozzy By default Commanded will set the event type to the event module's full namespace (prepended with `Elixir.`). This behaviour is implemented in the `Commanded.Serialization.ModuleNameTypeProvider` module, as shown below:

```elixir
defmodule Commanded.Serialization.ModuleNameTypeProvider do
  @moduledoc """
  A type provider that uses the Elixir module name
  Example:
    - %An.Event{} module mapped to "Elixir.An.Event".
  """

  @behaviour Commanded.EventStore.TypeProvider

  def to_string(struct), do: Atom.to_string(struct.__struct__)

  def to_struct(type) do
    type |> String.to_existing_atom() |> struct()
  end
end
```

You can write your own type name provider by implementing the `Commanded.EventStore.TypeProvider` behaviour in your own module. It's only two functions: `to_string/1` and `to_struct/1`. 

As an example, you could use just the event module name, excluding the namespace:

defmodule ExampleTypeProvider do  
  @behaviour Commanded.EventStore.TypeProvider

  def to_string(%Elixir.Foo.Events.BurgerRequested{}), do: "BurgerRequested"
  def to_struct("BurgerRequested"), do: %Elixir.Foo.Events.BurgerRequested{}
end

Then configure it in your environment config file (`config/config.exs`):

```elixir
config :commanded,
  type_provider: ExampleTypeProvider
```

I'm not entirely sure of your exact use case but events should be deserialized to the same module they were serialized from. Perhaps you need to separate the event modules into their own library or umbrella app to be referenced by both nodes? The events are the contracts for your application so it is acceptable to extract them into their own app to support shared use.

Does that help you out?

**Comment by drozzy** [comment]
Yes, this solves my issue completely.
Thank you.

P.S.: To answer you question about my use case: I'm not using umbrella apps. Instead, I actually have separate nodes doing rpc-calls to each other. They communicate through event-store events as a means for pub-sub. That is why I need to deserialize them in a different name space.

**Comment by drozzy** [comment]
Hm.. are you sure the config is right with `type_provided` key?

I did everything but no change in behavior...

**Comment by slashdotdash** [comment]
Sorry @drozzy, I forgot to say that you need to recompile the event store after changing this config setting. It's compiled into the event store using a macro. 

You need to run:

```console
$ mix deps.compile eventstore --force
```

Let me know if that still doesn't work.

**Comment by drozzy** [comment]
When I do this compile I get this really weird error:

`warning: function ModelAR.TypeProvider.to_struct/1 is undefined (module ModelAR.TypeProvider is not available)
  lib/commanded/serialization/json_serializer.ex:25`

Even though I have a module `ModelAR.TypeProvider` in the file `type_provider.ex`.

Now, it's probably me making some sort of typo, so I'll keep debugging. But maybe something jumps out at you?

**Comment by drozzy** [comment]
Keeps saying it's not defined. I do pretty much the same thing as in the standard type provider:

https://github.com/slashdotdash/commanded/blob/master/lib/commanded/serialization/module_name_type_provider.ex

**Comment by slashdotdash** [comment]
Yes, I've just tried to reproduce this and have encountered the same compilation error. The good news is that it does actually work when you run your application. 

I used the following type provider module which excludes the `Elixir.` prefix from type name:

```elixir
defmodule ExampleTypeProvider do
  @behaviour Commanded.EventStore.TypeProvider

  def to_string(struct) do
    "Elixir." <> type = Atom.to_string(struct.__struct__)
    type
  end

  def to_struct(type) do
    "Elixir." <> type |> String.to_existing_atom() |> struct()
  end
end
```

Peeking into the `events` table I can see it using the provider I've specified above. I'll have a think about how best to suppress that warning.

**Comment by drozzy** [comment]
Yap! It works. Thanks.

**Comment by drozzy** [comment]
P.S.: Just out of curiosity (and not being an expert in Elixir) why are you using macros?

**Comment by slashdotdash** [comment]
In this case it's only used for performance reasons. Reading the value from the application configuration is done once, at compile time, and not each time an event is (de)serialized. 

I'm reconsidering this approach now due to it not being very user friendly.

**Comment by drozzy** [comment]
Compared to read-times over the network, deserialization etc.. I think this is still going to be very fast, even if you read it anew every time.

But that's just my 2c haha.
