### ISSUE TITLE
[question] mnesia as an event store?

### ISSUE THREAD

**Issue by sunny-g** [slashdotdash/commanded#71]
I'm working on an open-source p2p application that I want to structure with your library, but don't want to require users to have to install anything other than BEAM and Elixir. I'm aware of the guidance you provided [here](https://github.com/slashdotdash/commanded#event-store-provider) with regards to custom adapters, but they seem relatively simple (presumably because your [eventstore](https://github.com/slashdotdash/eventstore) library is doing most of the heavy lifting).

Is my only option for using mnesia as the event store to write a library similar to [eventstore](https://github.com/slashdotdash/eventstore) and an adapter? If so, do you have any useful resources to point me towards, as I've only been writing in Elixir for a few months, and haven't yet messed with mnesia or amnesia?

Any help would be greatly appreciated, thank you!

PS: can't wait for the [conduit book](https://leanpub.com/buildingconduit) to come out!

**Comment by drozzy** [comment]
Mnesia is [fun](https://github.com/drozzy/frags), but boy does it take a lot of time away from your life haha.

**Comment by slashdotdash** [comment]
@sunny-g You could use the existing [in-memory](https://github.com/slashdotdash/commanded/blob/dab9f6168bd70d886bb0db3d395a9b1ae274a73b/lib/commanded/event_store/adapters/in_memory.ex) adapter as a basis for an mnesia event store. That should give you an foundation to build on. 

The behaviour you need to implement is given below:

```elixir
defmodule Commanded.EventStore do
  @type stream_uuid :: String.t
  @type start_from :: :origin | :current | integer
  @type stream_version :: integer
  @type subscription_name :: String.t
  @type source_uuid :: String.t
  @type snapshot :: SnapshotData.t
  @type reason :: term

  @doc """
  Append one or more events to a stream atomically.
  """
  @callback append_to_stream(stream_uuid, expected_version :: non_neg_integer, events :: list(EventData.t)) :: {:ok, stream_version} | {:error, reason}

  @doc """
  Streams events from the given stream, in the order in which they were originally written.
  """
  @callback stream_forward(stream_uuid, start_version :: non_neg_integer, read_batch_size :: non_neg_integer) :: Enumerable.t | {:error, :stream_not_found} | {:error, reason}

  @doc """
  Subscriber will be notified of every event persisted to any stream.
  """
  @callback subscribe_to_all_streams(subscription_name, subscriber :: pid, start_from) :: {:ok, subscription :: pid}
    | {:error, :subscription_already_exists}
    | {:error, reason}

  @doc """
  Acknowledge receipt and successful processing of the given event received from a subscription to an event stream.
  """
  @callback ack_event(pid, RecordedEvent.t) :: any

  @doc """
  Unsubscribe an existing subscriber from all event notifications.
  """
  @callback unsubscribe_from_all_streams(subscription_name) :: :ok

  @doc """
  Read a snapshot, if available, for a given source.
  """
  @callback read_snapshot(source_uuid) :: {:ok, snapshot} | {:error, :snapshot_not_found}

  @doc """
  Record a snapshot of the data and metadata for a given source
  """
  @callback record_snapshot(snapshot) :: :ok | {:error, reason}

  @doc """
  Delete a previously recorded snapshop for a given source
  """
  @callback delete_snapshot(source_uuid) :: :ok | {:error, reason}
end

**Comment by sunny-g** [comment]
@slashdotdash that's what I thought, thanks!

**Comment by sunny-g** [comment]
@slashdotdash fantastic, thanks for this, I'll share the link here when I get around to it.
