### ISSUE TITLE
App crashes when using README Supervision example

### ISSUE THREAD

**Issue by florish** [slashdotdash/commanded#72]
I tried using the Supervisor setup as described [in the README](https://github.com/slashdotdash/commanded#supervision), but the app then crashes on startup:

```
** (Mix) Could not start application my_app: MyApp.Application.start(:normal, []) returned an error: shutdown: failed to start child: MyApp.Supervisor
    ** (EXIT) shutdown: failed to start child: Commanded.Supervisor
        ** (EXIT) shutdown: failed to start child: Registry
            ** (EXIT) already started: #PID<0.226.0>
```

It seems that the example setup does not work anymore with Elixir 1.4+, due to the [Application inference](https://elixir-lang.org/blog/2017/01/05/elixir-v1-4-0-released/#application-inference) changes, causing `commanded` to be automatically started. Adding `Commanded.Supervisor` to the supervision tree causes the `Registry` to be started twice under the same process name.

I'm still new to Elixir and not entirely sure how this could be fixed, but wanted to open this issue to let you know. I'd be happy to help out with fixing the README and/or testing the fixed example supervision setup, if needed.

**Comment by slashdotdash** [comment]
@florish Thanks for the feedback, I'll update the README as its no longer necessary to include the `Commanded.Supervisor` in your supervisor. As you mentioned, the Commanded application gets started automatically and starts that supervisor.
