### ISSUE TITLE
[question] missing pieces (actuator, sensor, plants, etc...)?

### ISSUE THREAD

**Issue by sunny-g** [slashdotdash/commanded#73]
@gregoryyoung @slashdotdash read an interesting [article](https://medium.com/@drozzy/filling-the-gaps-in-cqrs-and-event-sourced-systems-taxonomy-of-system-components-49a23421e582) about event sourcing and how the pieces fit together and would very much appreciate your opinion on what it proposes.

It describes the familiar aggregates, process managers and projections in terms of their inputs and outputs, but also "fills in the gaps" with new terms and modules currently unaddressed (at least by my own understanding) by traditional event sourcing architectures.

![taxonomy](https://cdn-images-1.medium.com/max/1600/1*V5Q3LGHByZ3ctaAqyEk79g.png)

My questions are:

1. have you implemented modules fitting the description of actors, actuators, sensors, plants or controllers?
1. do you even find them necessary in the apps you've built with `commanded`?
1. in general, what's the recommended manner of incorporating new modules not derived from `commanded` into a `commanded`-based event sourcing system?
1. in my own application, I need to communicate with:
  - a blockchain where:
    - messages to the blockchain succeed or fail
    - messages from the blockchain might trigger aggregate updates or new processes
  - and other nodes over UDP sockets in a p2p fashion, where:
    - messages to nodes result in receiving an ACK or a message that might update an aggregate or start a process
    - messages from nodes at any time might that update an aggregate or start a process

How would you recommend I go about implementing these gateways - with some of these new patterns/modules or with a different pattern altogether?

Thanks for your time and your help with the other issue I opened!

**Comment by drozzy** [comment]
I know @sunny-g is present on Slack and asked this question there, so I would suggest maybe closing this here?
Seems a bit more like a question then an issue :)

Also, feel free to ask me about it on Slack (since that is my article and I use both extreme and commanded).
