### ISSUE TITLE
Metadata in command handler

### ISSUE THREAD

**Issue by sammkj** [slashdotdash/commanded#95]
Is it possible to have metadata available in command handler? My use-case is I need to attach some extra information like user IP address, user agent when calling third party APIs in command handlers.

**Comment by slashdotdash** [comment]
No, that's not possible at the moment. 

For now, you can include the required data as fields in the command:

```elixir
:ok = Router.dispatch(%ExampleCommand{ip_address: "127.0.0.1", user_agent: "Mozilla ..."})
```

You could also include a field in your command named `metadata` and pass the entire metadata map:

```elixir
metadata = %{ip_address: "127.0.0.1", user_agent: "Mozilla ..."}
:ok = Router.dispatch(%ExampleCommand{metadata: metadata}, metadata: metadata)
```

**Comment by sammkj** [comment]
Ok, gotcha!
